// packages/svelte/src/lib/inputs/ColorInput.svelte
<script lang="ts">
	import '@vuuui/styles/components/inputs/color_input.scss'
	import { Snippet } from 'svelte'

	let {
		value = $bindable(),
		placeholder,
		icon
	}: {
		value?: string
		placeholder?: string
		icon?: Snippet
	} = $props()
</script>

<label class="vuuui-color-input">
	<input type="color" bind:value {placeholder} />

	<div class="vuuui-icon">
		{#if icon}
			{@render icon()}
		{/if}
	</div>
	<div class="vuuui-placeholder">{placeholder}</div>
</label>

// packages/svelte/src/lib/components/inputs/ColorInput.vue
<script setup lang="ts">
import '@vuuui/styles/components/inputs/color_input.scss'

interface ColorInputProps {
  modelValue?: string
  placeholder?: string
}

defineProps<ColorInputProps>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: string): void
}>()

const onInputChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  emit('update:modelValue', target.value)
}
</script>

<template>
  <label class="vuuui-color-input">
    <input
      v-bind="$attrs"
      type="color"
      :value="modelValue"
      :placeholder="placeholder"
      @input="onInputChange"
    />

    <div class="vuuui-icon"><slot /></div>
    <div class="vuuui-placeholder">{{ placeholder }}</div>
  </label>
</template>
