// packages/solidjs/src/components/buttons/FilledButton.tsx
import { TextButtonBase } from "./TextButtonBase"
import type { TextButtonComponent } from "."
import "@vuuui/styles/components/buttons/filled_button.scss"

export const FilledButton: TextButtonComponent = (props) => {
	return <TextButtonBase
		defaultClassName="vuuui-filled-button"
		{...props}
	/>
}

// packages/svelte/src/lib/buttons/FilledButton.svelte
<script lang="ts">
	import TextButtonBase from './TextButtonBase.svelte'
	import type { TextButtonBaseProps } from './types.d.ts'
	import '@vuuui/styles/components/buttons/filled_button.scss'

	let props: TextButtonBaseProps = $props()
</script>

<TextButtonBase {...props} class="vuuui-filled-button {props.class}" />
