// packages/solidjs/src/components/buttons/TextButton.tsx
import { TextButtonBase } from "./TextButtonBase";
import type { TextButtonComponent } from ".";
import "@vuuui/styles/components/buttons/text_button.scss";

export const TextButton: TextButtonComponent = (props) => {
	return <TextButtonBase
		defaultClassName="vuuui-text-button"
		{...props}
	/>
}

// packages/svelte/src/lib/buttons/TextButton.svelte
<script lang="ts">
	import TextButtonBase from './TextButtonBase.svelte'
	import type { TextButtonBaseProps } from './types.d.ts'
	import '@vuuui/styles/components/buttons/text_button.scss'

	let props: TextButtonBaseProps = $props()
</script>

<TextButtonBase {...props} class="vuuui-text-button" />
