// packages/vue/src/components/buttons/TextButtonBase.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import ButtonBase from './ButtonBase.vue'
import { DuckSpinner } from '../..'
import type { ButtonBaseProps } from './types.d.ts'

defineProps<ButtonBaseProps>()
</script>

<template>
  <ButtonBase v-bind="$props">
    <div
      class="vuuui-body"
      :style="{ visibility: loading ? 'hidden' : 'initial' }"
    >
      <span v-if="$slots.icon" class="vuuui-icon">
        <slot name="icon" />
      </span>

      <span class="vuuui-content">
        <slot />
      </span>
    </div>

    <div v-if="loading" class="vuuui-spinner">
      <DuckSpinner />
    </div>
  </ButtonBase>
</template>

// packages/svelte/src/lib/buttons/TextButtonBase.svelte
<script lang="ts">
	import ButtonBase from './ButtonBase.svelte'
	import { DuckSpinner } from '../index.js'
	import type { TextButtonBaseProps } from './types.d.ts'

	let { children, loading, icon, ...stuff }: TextButtonBaseProps = $props()
</script>

{#snippet baseChildren()}
	<div class="vuuui-body" style:visibility={loading ? 'hidden' : 'initial'}>
		{#if icon}
			<span class="vuuui-icon">
				{@render icon()}
			</span>
		{/if}

		<span class="vuuui-content">
			{@render children()}
		</span>
	</div>

	{#if loading}
		<div class="vuuui-spinner">
			<DuckSpinner />
		</div>
	{/if}
{/snippet}

<ButtonBase children={baseChildren} {loading} {...stuff}></ButtonBase>
