// packages/svelte/src/lib/buttons/FilledButton.svelte
<script lang="ts">
	import TextButtonBase from './TextButtonBase.svelte'
	import type { TextButtonBaseProps } from './types.d.ts'
	import '@vuuui/styles/components/buttons/filled_button.scss'

	let props: TextButtonBaseProps = $props()
</script>

<TextButtonBase {...props} class="vuuui-filled-button {props.class}" />

// packages/vue/src/components/buttons/FilledButton.vue
<script setup lang="ts">
import { defineProps } from 'vue'
import TextButtonBase from './TextButtonBase.vue'
import '@vuuui/styles/components/buttons/filled_button.scss'
import type { ButtonBaseProps } from './types.d.ts'

defineProps<ButtonBaseProps>()
</script>

<template>
  <TextButtonBase v-bind="$props" class="vuuui-filled-button">
    <template #icon>
      <slot name="icon"></slot>
    </template>

    <template #default>
      <slot></slot>
    </template>
  </TextButtonBase>
</template>
