// packages/vue/preview/pages/components.page/Avatar.vue
<script setup lang="ts">
import { Avatar, Spacer } from '../../../src'
</script>

<template>
  <section>
    <h2>Avatar</h2>
    <br />

    <Spacer>
      <Avatar src="https://data.voz.vn/avatars/l/1756/1756218.jpg" />
      <Avatar
        size="84px"
        src="https://data.voz.vn/avatars/l/1785/1785236.jpg"
      />
      <Avatar
        alt="ahihi"
        size="96px"
        src="https://data.voz.vn/avatars/l/1895/1895294.jpg"
      />
    </Spacer>
  </section>
</template>

// packages/svelte/src/routes/components/avatar/+page.svelte
<script lang="ts">
	import { Avatar, Spacer } from '$lib/index.js'
</script>

<section>
	<h2>Avatar</h2>
	<br />

	<Spacer>
		<Avatar src="https://data.voz.vn/avatars/l/1756/1756218.jpg" />
		<Avatar size="84px" src="https://data.voz.vn/avatars/l/1785/1785236.jpg" />
		<Avatar alt="ahihi" size="96px" src="https://data.voz.vn/avatars/l/1895/1895294.jpg" />
	</Spacer>
</section>
