// packages/vue/src/components/buttons/ButtonBase.vue
<script setup lang="ts">
import { computed, defineProps } from 'vue'
import type { ButtonBaseProps } from './types.d.ts'

const props = defineProps<ButtonBaseProps>()
const isDisabled = computed(() => props.loading || props.disabled)
</script>

<template>
  <button
    :disabled="isDisabled"
    :active="active"
  >
    <slot />
  </button>
</template>

// packages/solidjs/src/components/buttons/ButtonBase.tsx
import { createMemo } from 'solid-js'
import type { ButtonBaseComponent } from '.'

export const ButtonBase: ButtonBaseComponent = (props) => {
	const isDisabled = createMemo(() => props.loading || props.disabled)

	const onClick = createMemo(() => {
		if (isDisabled()) return () => {}
		return props.onClick
	})

	const className = createMemo(() => {
		let className = props.defaultClassName || ''
		if (props.class) className += ' ' + props.class
		return className || undefined
	})

	return <button
		onClick={onClick()}
		disabled={isDisabled()}
		class={className()}
		{...props}
	/>
}
