// packages/svelte/src/lib/buttons/ElevatedButton.svelte
<script lang="ts">
	import TextButtonBase from './TextButtonBase.svelte'
	import type { TextButtonBaseProps } from './types.d.ts'
	import '@vuuui/styles/components/buttons/elevated_button.scss'

	let props: TextButtonBaseProps = $props()
</script>

<TextButtonBase {...props} class="vuuui-elevated-button {props.class}" />

// packages/solidjs/src/components/buttons/ElevatedButton.tsx
import { TextButtonBase } from './TextButtonBase'
import type { TextButtonComponent } from '.'
import '@vuuui/styles/components/buttons/elevated_button.scss'

export const ElevatedButton: TextButtonComponent = (props) => {
  return <TextButtonBase defaultClassName="vuuui-elevated-button" {...props} />
}
