// packages/svelte/src/lib/buttons/OutlinedButton.svelte
<script lang="ts">
	import TextButtonBase from './TextButtonBase.svelte'
	import type { TextButtonBaseProps } from './types.d.ts'
	import '@vuuui/styles/components/buttons/outlined_button.scss'

	let props: TextButtonBaseProps = $props()
</script>

<TextButtonBase {...props} class="vuuui-outlined-button" />

// packages/solidjs/src/components/buttons/OutlinedButton.tsx
import { TextButtonBase } from "./TextButtonBase"
import type { TextButtonComponent } from "."
import "@vuuui/styles/components/buttons/outlined_button.scss"

export const OutlinedButton: TextButtonComponent = (props) => {
	return <TextButtonBase
		defaultClassName="vuuui-outlined-button"
		{...props}
	/>
}
