// packages/svelte/src/lib/buttons/TextButtonBase.svelte
<script lang="ts">
	import ButtonBase from './ButtonBase.svelte'
	import { DuckSpinner } from '../index.js'
	import type { TextButtonBaseProps } from './types.d.ts'

	let { children, loading, icon, ...stuff }: TextButtonBaseProps = $props()
</script>

{#snippet baseChildren()}
	<div class="vuuui-body" style:visibility={loading ? 'hidden' : 'initial'}>
		{#if icon}
			<span class="vuuui-icon">
				{@render icon()}
			</span>
		{/if}

		<span class="vuuui-content">
			{@render children()}
		</span>
	</div>

	{#if loading}
		<div class="vuuui-spinner">
			<DuckSpinner />
		</div>
	{/if}
{/snippet}

<ButtonBase children={baseChildren} {loading} {...stuff}></ButtonBase>

// packages/solidjs/src/components/buttons/TextButtonBase.tsx
import { type JSX, createMemo } from 'solid-js'
import { ButtonBase } from './ButtonBase'
import { DuckSpinner } from '../..'
import type { TextButtonBaseComponent } from '.'

export const TextButtonBase: TextButtonBaseComponent = (props) => {
	const bodyStyle = createMemo(() => {
		if (props.loading) return {
			visibility: 'hidden',
		} as JSX.CSSProperties

		return undefined;
	})

	const iconEl = <span class='vuuui-icon'>{props.icon}</span>
	const spinnerEl = <div class='vuuui-spinner'><DuckSpinner /></div>

	return <ButtonBase {...props}>
		<div class='vuuui-body' style={bodyStyle()}>
			{props.icon && iconEl}
			<span class='vuuui-content'>{props.children}</span>
		</div>

		{props.loading && spinnerEl}
	</ButtonBase>
}
