// packages/svelte/src/lib/components/containment/Avatar.vue
<script setup lang="ts">
import '@vuuui/styles/components/containment/avatar.scss'

interface Props {
  src: string
  alt?: string
  size?: string
}

withDefaults(defineProps<Props>(), {
  alt: '',
  size: '64px',
})
</script>
m g
<template>
  <img class="vuuui-avatar" :style="{ width: size }" :src="src" :alt="alt" />
</template>

// packages/svelte/src/lib/containment/Avatar.svelte
<script lang="ts">
	import '@vuuui/styles/components/containment/avatar.scss'
	import type { HTMLImgAttributes } from 'svelte/elements'

	interface AvatarProps extends HTMLImgAttributes {
		size: string | number
	}

	let { size = '64px', ...rest }: AvatarProps = $props()
</script>

<img {...rest} class="vuuui-avatar {rest.class}" style:width={size} />
