// packages/vue/src/components/containment/Container.vue
<script setup lang="ts">
import '@vuuui/styles/components/containment/container.scss'

interface ContainerProps {
  xs?: boolean
  sm?: boolean
  md?: boolean
  fluid?: boolean
}

defineProps<ContainerProps>()
</script>

<template>
  <section
    class="vuuui-container"
    :data-xs="xs"
    :data-sm="sm"
    :data-md="md"
    :data-fluid="fluid"
  >
    <slot></slot>
  </section>
</template>

// packages/svelte/src/lib/containment/Container.svelte
<script lang="ts">
	import '@vuuui/styles/components/containment/container.scss'
	import type { Snippet } from 'svelte'

	let {
		children,
		xs,
		sm,
		md,
		fluid
	}: {
		children: Snippet
		xs?: boolean
		sm?: boolean
		md?: boolean
		fluid?: boolean
	} = $props()
</script>

<section class="vuuui-container" data-xs={xs} data-sm={sm} data-md={md} data-fluid={fluid}>
	{@render children()}
</section>
