// packages/svelte/src/lib/navigation/navigation_bar/NavigationBarButton.svelte
<script lang="ts">
	import type { HTMLAnchorAttributes } from 'svelte/elements'
	import type { Snippet } from 'svelte'
	import '@vuuui/styles/components/navigation/navigation_bar/navigation_bar_button.scss'

	interface NavigationBarButtonProps extends HTMLAnchorAttributes {
		icon: Snippet
		iconActive: Snippet
		active?: boolean
	}

	let { active, icon, iconActive, children, ...rest }: NavigationBarButtonProps = $props()
</script>

<a {...rest} class="vuuui-navigation-bar-button {rest.class}" data-active={active}>
	<div class="vuuui-icon">
		{#if active}
			{@render iconActive()}
		{:else}
			{@render icon()}
		{/if}
	</div>

	{#if children}
		{@render children()}
	{/if}
</a>

// packages/vue/src/components/navigation/navigation_bar/NavigationBarButton.vue
<script setup lang="ts">
import '@vuuui/styles/components/navigation/navigation_bar/navigation_bar_button.scss'

interface NavigationBarButtonProps {
  active?: boolean
}

defineProps<NavigationBarButtonProps>()
</script>

<template>
  <button class="vuuui-navigation-bar-button" :data-active="active">
    <div class="vuuui-icon">
      <slot v-if="active" name="iconActive" />
      <slot v-else name="icon" />
    </div>

    <slot />
  </button>
</template>
