// packages/solidjs/src/components/navigation/app_bar/AppBar.tsx
import { createMemo } from "solid-js"
import { AppBarComponent } from ".."
import "@vuuui/styles/components/navigation/app_bar.scss"

export const AppBar: AppBarComponent = (props) => {
  const className = createMemo(() => {
		let c = 'vuuui-app-bar '
		if (props.class) c += props.class
		return c
	})

  return <section {...props} class={className()}>
    <div class="vuuui-app-bar-section-left">
      <div class="vuuui-app-bar-leading">
        {props.leading}
      </div>

      <div class="vuuui-app-bar-title">
        {props.title}
      </div>
    </div>

    <div class="vuuui-app-bar-actions">
      {props.actions}
    </div>
  </section>
}

// packages/vue/src/components/navigation/AppBar.vue
<script setup lang="ts">
import '@vuuui/styles/components/navigation/app_bar.scss'
</script>

<template>
  <section class="vuuui-app-bar">
    <div class="vuuui-app-bar-section-left">
      <div class="vuuui-app-bar-leading">
        <slot name="leading" />
      </div>

      <div class="vuuui-app-bar-title">
        <slot name="title" />
      </div>
    </div>

    <div class="vuuui-app-bar-actions">
      <slot name="actions"></slot>
    </div>
  </section>
</template>
