// packages/svelte/src/lib/containment/Spacer.svelte
<script lang="ts">
	import '@vuuui/styles/components/containment/spacer.scss'
	import type { Property } from 'csstype'
	import type { Snippet } from 'svelte'

	let {
		children,
		gap,
		wrap,
		justify,
		align,
		direction
	}: {
		children: Snippet
		gap?: Property.Gap
		wrap?: Property.FlexWrap
		justify?: Property.JustifyContent
		align?: Property.AlignItems
		direction?: Property.FlexDirection
	} = $props()
</script>

<div
	class="vuuui-spacer"
	style:gap
	style:flex-wrap={wrap}
	style:justify-content={justify}
	style:align-items={align}
	style:flex-direction={direction}
>
	{@render children()}
</div>

// packages/solidjs/src/components/layout/spacer/Spacer.tsx
import { createMemo } from "solid-js"
import type { JSX } from "solid-js"
import type { SpacerComponent } from './'
import "@vuuui/styles/components/buttons/elevated_button.scss"
import '@vuuui/styles/components/layout/spacer.scss'

export const Spacer: SpacerComponent = (props) => {
	const style = createMemo(() => {
		return {
			gap: props.gap,
			"flex-wrap": props.wrap,
			"justify-content": props.justify,
			"align-items": props.align,
		} as JSX.CSSProperties;
	});

	const className = createMemo(() => {
		let className = 'vuuui-spacer ';
		if (props.class) className += props.class;
		return className;
	});
	
	return <div
		style={style()}
		class={className()}
		{...props}
	/>
}
