// packages/solidjs/src/components/layout/container/Container.tsx
import { createMemo } from 'solid-js'
import type { ContainerComponent } from '.'
import '@vuuui/styles/components/layout/container.scss'

export const Container: ContainerComponent = (props) => {
  const className = createMemo(() => {
    let className = 'vuuui-container '
    if (props.class) className += props.class
    return className
  })

  return <section {...props} class={className()} />
}

// packages/vue/src/components/layout/Container.vue
<script setup lang="ts">
import { computed } from 'vue'
import '@vuuui/styles/components/layout/container.scss'

interface ContainerProps {
  xs?: boolean
  sm?: boolean
  md?: boolean
}

defineProps<ContainerProps>()
</script>

<template>
  <section class="vuuui-container" v-bind="{ xs, sm, md }">
    <slot></slot>
  </section>
</template>
