// packages/svelte/src/lib/containment/Spacer.svelte
<script lang="ts">
	import '@vuuui/styles/components/containment/spacer.scss'
	import type { Property } from 'csstype'
	import type { Snippet } from 'svelte'

	let {
		children,
		gap,
		wrap,
		justify,
		align,
		direction
	}: {
		children: Snippet
		gap?: Property.Gap
		wrap?: Property.FlexWrap
		justify?: Property.JustifyContent
		align?: Property.AlignItems
		direction?: Property.FlexDirection
	} = $props()
</script>

<div
	class="vuuui-spacer"
	style:gap
	style:flex-wrap={wrap}
	style:justify-content={justify}
	style:align-items={align}
	style:flex-direction={direction}
>
	{@render children()}
</div>

// packages/vue/src/components/containment/Spacer.vue
<script setup lang="ts">
import '@vuuui/styles/components/containment/spacer.scss'
import type { Property } from 'csstype'

interface SpacerProps {
  gap?: Property.Gap
  wrap?: Property.FlexWrap
  justify?: Property.JustifyContent
  align?: Property.AlignItems
  direction?: Property.FlexDirection
}

defineProps<SpacerProps>()
</script>

<template>
  <div
    :style="{
      gap: gap,
      justifyContent: justify,
      alignItems: align,
      flexWrap: wrap,
      flexDirection: direction,
    }"
    class="vuuui-spacer"
  >
    <slot></slot>
  </div>
</template>
