// packages/solidjs/src/components/inputs/FileInput.tsx
import { createRenderEffect } from 'solid-js'
import type { FileInputComponent } from '.'
import '@vuuui/styles/components/inputs/file_input.scss'

export const FileInput: FileInputComponent = (props) => {
  const [files, setFiles] = props.model || []

  const onRef = (el: HTMLInputElement) => {
    createRenderEffect(() => {
      if (files) el.files = files()
    })

    el.addEventListener('change', () => {
      if (setFiles) setFiles(el.files)
    })
  }

  return (
    <label class="vuuui-file-input">
      <input {...props} type="file" ref={onRef} />
      <div class="vuuui-icon">{props.icon}</div>
      <div class="vuuui-placeholder">{props.placeholder}</div>
    </label>
  )
}

// packages/svelte/src/lib/inputs/FileInput.svelte
<script lang="ts">
	import '@vuuui/styles/components/inputs/file_input.scss'
	import { Snippet } from 'svelte'

	let {
		icon,
		files,
		placeholder
	}: {
		icon?: Snippet
		files?: FileList
		placeholder?: string
	} = $props()
</script>

<label class="vuuui-file-input">
	<input type="file" bind:files {placeholder} />

	<div class="vuuui-icon">
		{#if icon}
			{@render icon()}
		{/if}
	</div>

	<div class="vuuui-placeholder">
		{placeholder}
	</div>
</label>
