// packages/svelte/src/lib/components/inputs/Radio.vue
<script setup lang="ts">
import '@vuuui/styles/components/inputs/radio_input.scss'

interface RadioProps {
  placeholder?: string
}

defineProps<RadioProps>()
</script>

<template>
  <label class="vuuui-radio">
    <input v-bind="$attrs" type="radio" />

    <div class="vuuui-icon">
      <div class="vuuui-checkmark">
        <span>&#10004;</span>
      </div>
    </div>

    {{ placeholder }}
  </label>
</template>

// packages/svelte/src/lib/inputs/Radio.svelte
<script lang="ts">
	import '@vuuui/styles/components/inputs/radio_input.scss'

	let {
		placeholder,
		value,
		group = $bindable()
	}: {
		placeholder?: string
		value?: string
		group?: string
	} = $props()
</script>

<label class="vuuui-radio">
	<input type="radio" {value} bind:group />

	<div class="vuuui-icon">
		<div class="vuuui-checkmark">
			<span>&#10004;</span>
		</div>
	</div>

	{placeholder}
</label>
