// packages/vue/src/components/inputs/Slider.vue
<script setup lang="ts">
import '@vuuui/styles/components/inputs/slider.scss'

interface SliderProps {
  modelValue?: number
  min?: number
  max?: number
  step?: number
}

defineProps<SliderProps>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: number): void
}>()

function onInput(e: Event) {
  const target = e.target as HTMLInputElement
  emit('update:modelValue', Number(target.value))
}
</script>

<template>
  <div class="vuuui-slider-wrapper">
    <input
      type="range"
      class="vuuui-slider"
      v-bind="{ min, max, step }"
      :style="{
        '--val': modelValue || 50,
        '--min': min || 0,
        '--max': max || 100,
      }"
      :value="modelValue"
      @input="onInput"
    />
  </div>
</template>

// packages/svelte/src/lib/inputs/Slider.svelte
<script lang="ts">
	import '@vuuui/styles/components/inputs/slider.scss'

	let {
		value = $bindable(),
		min,
		max,
		step
	}: {
		value?: number
		min?: number
		max?: number
		step?: number
	} = $props()
</script>

<div class="vuuui-slider-wrapper">
	<input
		type="range"
		class="vuuui-slider"
		bind:value
		{min}
		{max}
		{step}
		style:--val={value || 0}
		style:--min={min || 0}
		style:--max={max || 100}
	/>
</div>
