// packages/svelte/src/lib/components/inputs/Switch.vue
<script setup lang="ts">
import '@vuuui/styles/components/inputs/switch.scss'

interface SwitchProps {
  modelValue?: boolean
  placeholder?: string
}

defineProps<SwitchProps>()

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
}>()

const onInputChange = (e: Event) => {
  const target = e.target as HTMLInputElement
  emit('update:modelValue', target.checked)
}
</script>

<template>
  <label class="vuuui-switch">
    <input
      v-bind="$attrs"
      type="checkbox"
      :checked="modelValue"
      @input="onInputChange"
    />

    <div class="vuuui-switch-button">
      <div class="vuuui-switch-dot" />
    </div>

    {{ placeholder }}
  </label>
</template>

// packages/svelte/src/lib/inputs/Switch.svelte
<script lang="ts">
	import '@vuuui/styles/components/inputs/switch.scss'

	let {
		checked = $bindable(),
		placeholder
	}: {
		checked?: boolean
		placeholder?: string
	} = $props()
</script>

<label class="vuuui-switch">
	<input type="checkbox" bind:checked />

	<div class="vuuui-switch-button">
		<div class="vuuui-switch-dot"></div>
	</div>

	{placeholder}
</label>
