// packages/svelte/src/lib/components/navigation/navigation_bar/NavigationBarButton.vue
<script setup lang="ts">
import '@vuuui/styles/components/navigation/navigation_bar/navigation_bar_button.scss'

interface NavigationBarButtonProps {
  active?: boolean
}

defineProps<NavigationBarButtonProps>()
</script>

<template>
  <button class="vuuui-navigation-bar-button" :active="active">
    <div class="vuuui-icon">
      <slot v-if="active" name="iconActive" />
      <slot v-else name="icon" />
    </div>

    <slot />
  </button>
</template>

// packages/solidjs/src/components/navigation/navigation_bar/NavigationBarButton.tsx
import { createMemo } from 'solid-js'
import type { NavigationBarButtonComponent } from './'
import '@vuuui/styles/components/navigation/navigation_bar/navigation_bar_button.scss';

export const NavigationBarButton: NavigationBarButtonComponent = (props) => {
	const icon = createMemo(() => {
		if (props.active && props.iconActive) return props.iconActive
		return props.icon
	})

	const className = createMemo(() =>
		'vuuui-navigation-bar-button ' + (props.class || '')
	)

	return <button {...props} class={className()}>
		<div class='vuuui-icon'> {icon()} </div>
		{props.children}
	</button>
}
