// packages/solidjs/src/components/navigation/navigation_bar/NavigationBar.tsx
import { createMemo } from 'solid-js'
import type { NavigationBarComponent } from './types'
import '@vuuui/styles/components/navigation/navigation_bar/navigation_bar.scss'

export const NavigationBar: NavigationBarComponent = props => {
	const className = createMemo(() => {
		let c = 'vuuui-navigation-bar '
		if (props.class) c += props.class
		return c
	})

	return <section
		{...props}
		class={className()}
	/>
}

// packages/svelte/src/lib/navigation/navigation_bar/NavigationBar.svelte
<script lang="ts">
	import type { HTMLAttributes } from 'svelte/elements'
	import '@vuuui/styles/components/navigation/navigation_bar/navigation_bar.scss'

	let { children, ...rest }: HTMLAttributes<HTMLElement> = $props()
</script>

<section {...rest} class="vuuui-navigation-bar {rest.class}">
	{#if children}
		{@render children()}
	{/if}
</section>
